name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install FVM
        run: |
          dart pub global activate fvm
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Setup Flutter
        run: fvm install
      - name: Verify Flutter version
        run: fvm flutter --version
      - run: fvm flutter pub get
      - run: fvm flutter test
      - run: fvm flutter pub publish --dry-run
      - name: Publish to pub.dev
        run: fvm flutter pub publish -f
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}